DROP TABLE IF EXISTS photos;
CREATE TABLE photos (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    url TEXT,
    description TEXT NOT NULL
);
